import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Peoplescreen(),
        ]),
      ),
    );
  }
}

class Peoplescreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 492.78,
          height: 851.42,
          padding: const EdgeInsets.only(left: 22.39, right: 22.40),
          decoration: BoxDecoration(
            color: Colors.black.withValues(alpha: 0.60),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Container(
                width: 448,
                height: 400.17,
                padding: const EdgeInsets.only(top: 0.55),
                clipBehavior: Clip.antiAlias,
                decoration: ShapeDecoration(
                  color: const Color(0xFF1A1D24),
                  shape: RoundedRectangleBorder(
                    side: BorderSide(
                      width: 0.55,
                      color: const Color(0xFF2A2F3A),
                    ),
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(28),
                      topRight: Radius.circular(28),
                    ),
                  ),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      width: double.infinity,
                      height: 399.63,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 204,
                            top: 24,
                            child: Container(
                              width: 40,
                              height: 4,
                              decoration: ShapeDecoration(
                                color: const Color(0xFF2A2F3A),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(18372300),
                                ),
                              ),
                            ),
                          ),
                          Positioned(
                            left: 24,
                            top: 51.99,
                            child: Container(
                              width: 400,
                              height: 26,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: -0.45,
                                    child: Text(
                                      'Add Friend',
                                      style: TextStyle(
                                        color: const Color(0xFFEDEFF3),
                                        fontSize: 20,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w600,
                                        height: 1.30,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          Positioned(
                            left: 24,
                            top: 101.99,
                            child: Container(
                              width: 400,
                              height: 237.64,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 19.99,
                                children: [
                                  Container(
                                    width: double.infinity,
                                    height: 71.58,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 6,
                                      children: [
                                        Container(
                                          width: double.infinity,
                                          height: 19.51,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0.64,
                                                child: Text(
                                                  'Name or username',
                                                  style: TextStyle(
                                                    color: const Color(0xFF9AA0A6),
                                                    fontSize: 13,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.50,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          height: 46.08,
                                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF222633),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 0.55,
                                                color: const Color(0xFF2A2F3A),
                                              ),
                                              borderRadius: BorderRadius.circular(12),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                'Search by name or @username',
                                                style: TextStyle(
                                                  color: const Color(0xFF5A5F6A),
                                                  fontSize: 14,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: double.infinity,
                                    height: 71.58,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 6,
                                      children: [
                                        Container(
                                          width: double.infinity,
                                          height: 19.51,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0.64,
                                                child: Text(
                                                  'Or invite via email',
                                                  style: TextStyle(
                                                    color: const Color(0xFF9AA0A6),
                                                    fontSize: 13,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.50,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Container(
                                          width: double.infinity,
                                          height: 46.08,
                                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF222633),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 0.55,
                                                color: const Color(0xFF2A2F3A),
                                              ),
                                              borderRadius: BorderRadius.circular(12),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                'friend@example.com',
                                                style: TextStyle(
                                                  color: const Color(0xFF5A5F6A),
                                                  fontSize: 14,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: double.infinity,
                                    height: 54.49,
                                    decoration: ShapeDecoration(
                                      gradient: LinearGradient(
                                        begin: Alignment(0.00, 0.50),
                                        end: Alignment(1.00, 0.50),
                                        colors: [const Color(0xFF4F6EF7), const Color(0xFF5371F8), const Color(0xFF5673F8), const Color(0xFF5A76F9), const Color(0xFF5E79FA), const Color(0xFF627BFA), const Color(0xFF657EFB), const Color(0xFF6980FC), const Color(0xFF6D83FC), const Color(0xFF7186FD), const Color(0xFF7488FE), const Color(0xFF788BFE), const Color(0xFF7C8DFF)],
                                      ),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(16),
                                      ),
                                      shadows: [
                                        BoxShadow(
                                          color: Color(0x664F6EF7),
                                          blurRadius: 20,
                                          offset: Offset(0, 4),
                                          spreadRadius: 0,
                                        )
                                      ],
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 159.62,
                                          top: 14.64,
                                          child: Text(
                                            'Send Invite',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 15,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w600,
                                              height: 1.50,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}