import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Groupdetail(),
        ]),
      ),
    );
  }
}

class Groupdetail extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 492.78,
          height: 851.42,
          padding: const EdgeInsets.only(left: 22.39, right: 22.40),
          decoration: BoxDecoration(color: const Color(0xFF12141A)),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: double.infinity,
                height: 750.11,
                child: Stack(
                  children: [
                    Positioned(
                      left: 19.99,
                      top: 24,
                      child: Container(
                        width: 56.04,
                        height: 20.99,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 1.99,
                              child: Container(
                                width: 17,
                                height: 17,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Stack(),
                              ),
                            ),
                            Positioned(
                              left: 22,
                              top: -0.36,
                              child: Text(
                                ' Back',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: const Color(0xFF9AA0A6),
                                  fontSize: 14,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1.50,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19.99,
                      top: 68.99,
                      child: Container(
                        width: 408.01,
                        height: 63.99,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 16,
                          children: [
                            Container(
                              width: 63.99,
                              height: 63.99,
                              decoration: ShapeDecoration(
                                color: const Color(0xFF222633),
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 0.55,
                                    color: const Color(0xFF2A2F3A),
                                  ),
                                  borderRadius: BorderRadius.circular(14),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Text(
                                    '🏠',
                                    style: TextStyle(
                                      color: const Color(0xFFEDEFF3),
                                      fontSize: 28,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.50,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Expanded(
                              child: Container(
                                height: 52.10,
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 4,
                                  children: [
                                    Container(
                                      width: double.infinity,
                                      height: 28.60,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0.55,
                                            child: Text(
                                              'Roommates',
                                              style: TextStyle(
                                                color: const Color(0xFFEDEFF3),
                                                fontSize: 22,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w600,
                                                height: 1.30,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: double.infinity,
                                      height: 19.51,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0.64,
                                            child: Text(
                                              '2 members',
                                              style: TextStyle(
                                                color: const Color(0xFF9AA0A6),
                                                fontSize: 13,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19.99,
                      top: 164.98,
                      child: Container(
                        width: 408.01,
                        height: 189.16,
                        decoration: ShapeDecoration(
                          color: const Color(0xFF1A1D24),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 0.55,
                              color: const Color(0xFF2A2F3A),
                            ),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          shadows: [
                            BoxShadow(
                              color: Color(0x66000000),
                              blurRadius: 32,
                              offset: Offset(0, 8),
                              spreadRadius: 0,
                            )
                          ],
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 24.55,
                              top: 24.54,
                              child: Container(
                                width: 358.92,
                                height: 18,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 123.53,
                                      top: 0.64,
                                      child: Text(
                                        'GROUP BALANCE',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF9AA0A6),
                                          fontSize: 12,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w500,
                                          height: 1.50,
                                          letterSpacing: 0.72,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24.55,
                              top: 50.54,
                              child: Container(
                                width: 358.92,
                                height: 43.99,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 104,
                                      top: -0.74,
                                      child: Text(
                                        '-\$67.00',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: const Color(0xFF8E7CFF),
                                          fontSize: 40,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w700,
                                          height: 1.10,
                                          letterSpacing: -1,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 24.55,
                              top: 118.53,
                              child: Container(
                                width: 358.92,
                                height: 46.08,
                                padding: const EdgeInsets.symmetric(horizontal: 73.10),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 11.99,
                                  children: [
                                    Container(
                                      width: 95.95,
                                      height: 46.08,
                                      decoration: ShapeDecoration(
                                        gradient: LinearGradient(
                                          begin: Alignment(0.00, 0.50),
                                          end: Alignment(1.00, 0.50),
                                          colors: [const Color(0xFF4F6EF7), const Color(0xFF5371F8), const Color(0xFF5673F8), const Color(0xFF5A76F9), const Color(0xFF5E79FA), const Color(0xFF627BFA), const Color(0xFF657EFB), const Color(0xFF6980FC), const Color(0xFF6D83FC), const Color(0xFF7186FD), const Color(0xFF7488FE), const Color(0xFF788BFE), const Color(0xFF7C8DFF)],
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(14),
                                        ),
                                        shadows: [
                                          BoxShadow(
                                            color: Color(0x4C4F6EF7),
                                            blurRadius: 16,
                                            offset: Offset(0, 4),
                                            spreadRadius: 0,
                                          )
                                        ],
                                      ),
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 24,
                                            top: 15.54,
                                            child: Container(
                                              width: 15,
                                              height: 15,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: BoxDecoration(),
                                              child: Stack(),
                                            ),
                                          ),
                                          Positioned(
                                            left: 46.99,
                                            top: 12.18,
                                            child: Text(
                                              'Pay',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Colors.white,
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w600,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 104.77,
                                      height: 46.08,
                                      decoration: ShapeDecoration(
                                        color: const Color(0xFF222633),
                                        shape: RoundedRectangleBorder(
                                          side: BorderSide(
                                            width: 0.55,
                                            color: const Color(0xFF2A2F3A),
                                          ),
                                          borderRadius: BorderRadius.circular(14),
                                        ),
                                      ),
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 20.54,
                                            top: 15.54,
                                            child: Container(
                                              width: 15,
                                              height: 15,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: BoxDecoration(),
                                              child: Stack(),
                                            ),
                                          ),
                                          Positioned(
                                            left: 43.54,
                                            top: 12.18,
                                            child: Text(
                                              'Notify',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: const Color(0xFFEDEFF3),
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w500,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19.99,
                      top: 378.13,
                      child: Container(
                        width: 408.01,
                        height: 16.50,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.64,
                              child: Text(
                                'MEMBERS',
                                style: TextStyle(
                                  color: const Color(0xFF9AA0A6),
                                  fontSize: 11,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1.50,
                                  letterSpacing: 0.88,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19.99,
                      top: 410.64,
                      child: Container(
                        width: 408.01,
                        height: 129.61,
                        padding: const EdgeInsets.all(0.55),
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          color: const Color(0xFF1A1D24),
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 0.55,
                              color: const Color(0xFF2A2F3A),
                            ),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          shadows: [
                            BoxShadow(
                              color: Color(0x66000000),
                              blurRadius: 32,
                              offset: Offset(0, 8),
                              spreadRadius: 0,
                            )
                          ],
                        ),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 0,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 64.53,
                              padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 14),
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 0.55,
                                    color: const Color(0xFF222633),
                                  ),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 11.99,
                                children: [
                                  Container(
                                    width: 35.99,
                                    height: 35.99,
                                    padding: const EdgeInsets.only(left: 13.79, right: 13.80),
                                    decoration: ShapeDecoration(
                                      color: const Color(0xFF2A2F3A),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(18372300),
                                      ),
                                      shadows: [
                                        BoxShadow(
                                          color: Color(0x19FFFFFF),
                                          blurRadius: 0,
                                          offset: Offset(0, 0),
                                          spreadRadius: 1,
                                        )
                                      ],
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 8.40,
                                          height: 19.51,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0.64,
                                                child: Text(
                                                  'S',
                                                  style: TextStyle(
                                                    color: const Color(0xFFEDEFF3),
                                                    fontSize: 13,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.50,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 20.99,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: -0.36,
                                            child: Text(
                                              'Sarah Chen',
                                              style: TextStyle(
                                                color: const Color(0xFFEDEFF3),
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w500,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              height: 63.98,
                              padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 14),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 11.99,
                                children: [
                                  Container(
                                    width: 35.99,
                                    height: 35.99,
                                    padding: const EdgeInsets.symmetric(horizontal: 14.07),
                                    decoration: ShapeDecoration(
                                      color: const Color(0xFF2A2F3A),
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(18372300),
                                      ),
                                      shadows: [
                                        BoxShadow(
                                          color: Color(0x19FFFFFF),
                                          blurRadius: 0,
                                          offset: Offset(0, 0),
                                          spreadRadius: 1,
                                        )
                                      ],
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 7.85,
                                          height: 19.51,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0.64,
                                                child: Text(
                                                  'E',
                                                  style: TextStyle(
                                                    color: const Color(0xFFEDEFF3),
                                                    fontSize: 13,
                                                    fontFamily: 'Inter',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.50,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Expanded(
                                    child: Container(
                                      height: 20.99,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: -0.36,
                                            child: Text(
                                              'Emily Zhang',
                                              style: TextStyle(
                                                color: const Color(0xFFEDEFF3),
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w500,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19.99,
                      top: 564.25,
                      child: Container(
                        width: 408.01,
                        height: 16.50,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0.64,
                              child: Text(
                                'TRANSACTIONS',
                                style: TextStyle(
                                  color: const Color(0xFF9AA0A6),
                                  fontSize: 11,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w500,
                                  height: 1.50,
                                  letterSpacing: 0.88,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 19.99,
                      top: 596.75,
                      child: Container(
                        width: 408.01,
                        height: 153.36,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 11.99,
                          children: [
                            Container(
                              width: double.infinity,
                              height: 70.68,
                              padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 16),
                              decoration: ShapeDecoration(
                                color: const Color(0xFF1A1D24),
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 0.55,
                                    color: const Color(0xFF2A2F3A),
                                  ),
                                  borderRadius: BorderRadius.circular(20),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x66000000),
                                    blurRadius: 32,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 16,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 37.59,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 321.99,
                                              height: 19.59,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 0,
                                                    top: 0.10,
                                                    child: Text(
                                                      'Groceries',
                                                      style: TextStyle(
                                                        color: const Color(0xFFEDEFF3),
                                                        fontSize: 14,
                                                        fontFamily: 'Inter',
                                                        fontWeight: FontWeight.w500,
                                                        height: 1.40,
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 20.23,
                                            child: Text(
                                              'Sarah Chen • Apr 15',
                                              style: TextStyle(
                                                color: const Color(0xFF9AA0A6),
                                                fontSize: 12,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Container(
                                    width: 28.93,
                                    height: 20.99,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: -1,
                                          top: -0.90,
                                          child: Text(
                                            '\$45',
                                            textAlign: TextAlign.right,
                                            style: TextStyle(
                                              color: const Color(0xFF8E7CFF),
                                              fontSize: 15,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w600,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: double.infinity,
                              height: 70.68,
                              padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 16),
                              decoration: ShapeDecoration(
                                color: const Color(0xFF1A1D24),
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 0.55,
                                    color: const Color(0xFF2A2F3A),
                                  ),
                                  borderRadius: BorderRadius.circular(20),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x66000000),
                                    blurRadius: 32,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 16,
                                children: [
                                  Expanded(
                                    child: Container(
                                      height: 37.59,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0,
                                            child: Container(
                                              width: 322.47,
                                              height: 19.59,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 0,
                                                    top: 0.10,
                                                    child: Text(
                                                      'Utilities',
                                                      style: TextStyle(
                                                        color: const Color(0xFFEDEFF3),
                                                        fontSize: 14,
                                                        fontFamily: 'Inter',
                                                        fontWeight: FontWeight.w500,
                                                        height: 1.40,
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0,
                                            top: 20.23,
                                            child: Text(
                                              'Emily Zhang • Apr 12',
                                              style: TextStyle(
                                                color: const Color(0xFF9AA0A6),
                                                fontSize: 12,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Container(
                                    width: 28.45,
                                    height: 20.99,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: -0.90,
                                          child: Text(
                                            '\$22',
                                            textAlign: TextAlign.right,
                                            style: TextStyle(
                                              color: const Color(0xFF8E7CFF),
                                              fontSize: 15,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w600,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}