import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Grouplist(),
        ]),
      ),
    );
  }
}

class Grouplist extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 493,
          height: 851,
          decoration: BoxDecoration(color: const Color(0xFF12141A)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 492.78,
                  height: 851.42,
                  padding: const EdgeInsets.only(left: 22.39, right: 22.40),
                  decoration: BoxDecoration(color: const Color(0xFF12141A)),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 600.61,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 19.99,
                              top: 24,
                              child: Container(
                                width: 408.01,
                                height: 39.49,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 257.62,
                                  children: [
                                    Container(
                                      width: 72.91,
                                      height: 28.60,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 0,
                                            top: 0.55,
                                            child: Text(
                                              'People',
                                              style: TextStyle(
                                                color: const Color(0xFFEDEFF3),
                                                fontSize: 22,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w600,
                                                height: 1.30,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 77.48,
                                      height: 39.49,
                                      decoration: ShapeDecoration(
                                        gradient: LinearGradient(
                                          begin: Alignment(0.00, 0.50),
                                          end: Alignment(1.00, 0.50),
                                          colors: [const Color(0xFF4F6EF7), const Color(0xFF5371F8), const Color(0xFF5673F8), const Color(0xFF5A76F9), const Color(0xFF5E79FA), const Color(0xFF627BFA), const Color(0xFF657EFB), const Color(0xFF6980FC), const Color(0xFF6D83FC), const Color(0xFF7186FD), const Color(0xFF7488FE), const Color(0xFF788BFE), const Color(0xFF7C8DFF)],
                                        ),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                        shadows: [
                                          BoxShadow(
                                            color: Color(0x4C4F6EF7),
                                            blurRadius: 12,
                                            offset: Offset(0, 2),
                                            spreadRadius: 0,
                                          )
                                        ],
                                      ),
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 16,
                                            top: 12.75,
                                            child: Container(
                                              width: 14,
                                              height: 14,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: BoxDecoration(),
                                              child: Stack(),
                                            ),
                                          ),
                                          Positioned(
                                            left: 35.99,
                                            top: 10.64,
                                            child: Text(
                                              'Add',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Colors.white,
                                                fontSize: 13,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w600,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 19.99,
                              top: 87.49,
                              child: Container(
                                width: 408.01,
                                height: 48.58,
                                padding: const EdgeInsets.all(4),
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF1A1D24),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 0.55,
                                      color: const Color(0xFF2A2F3A),
                                    ),
                                    borderRadius: BorderRadius.circular(14),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 4,
                                  children: [
                                    Expanded(
                                      child: Container(
                                        height: 39.49,
                                        decoration: ShapeDecoration(
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                        ),
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 67.18,
                                              top: 12.75,
                                              child: Container(
                                                width: 14,
                                                height: 14,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: Stack(),
                                              ),
                                            ),
                                            Positioned(
                                              left: 87.18,
                                              top: 10.64,
                                              child: Text(
                                                'People',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: const Color(0xFF9AA0A6),
                                                  fontSize: 13,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1.50,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Expanded(
                                      child: Container(
                                        height: 39.49,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF222633),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                          shadows: [
                                            BoxShadow(
                                              color: Color(0x4C000000),
                                              blurRadius: 8,
                                              offset: Offset(0, 2),
                                              spreadRadius: 0,
                                            )
                                          ],
                                        ),
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 65.86,
                                              top: 12.75,
                                              child: Container(
                                                width: 14,
                                                height: 14,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: Stack(),
                                              ),
                                            ),
                                            Positioned(
                                              left: 85.85,
                                              top: 10.64,
                                              child: Text(
                                                'Groups',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: const Color(0xFFEDEFF3),
                                                  fontSize: 13,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w600,
                                                  height: 1.50,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 19.99,
                              top: 222.13,
                              child: Container(
                                width: 408.01,
                                height: 378.48,
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  spacing: 19.99,
                                  children: [
                                    Container(
                                      width: double.infinity,
                                      height: 174.13,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        spacing: 11.99,
                                        children: [
                                          Container(
                                            width: double.infinity,
                                            height: 16.50,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 4,
                                                  top: 0.64,
                                                  child: Text(
                                                    'ACTIVE',
                                                    style: TextStyle(
                                                      color: const Color(0xFF9AA0A6),
                                                      fontSize: 11,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w500,
                                                      height: 1.50,
                                                      letterSpacing: 0.88,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Container(
                                            width: double.infinity,
                                            height: 145.63,
                                            padding: const EdgeInsets.all(0.55),
                                            clipBehavior: Clip.antiAlias,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1A1D24),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 0.55,
                                                  color: const Color(0xFF2A2F3A),
                                                ),
                                                borderRadius: BorderRadius.circular(18),
                                              ),
                                              shadows: [
                                                BoxShadow(
                                                  color: Color(0x66000000),
                                                  blurRadius: 32,
                                                  offset: Offset(0, 8),
                                                  spreadRadius: 0,
                                                )
                                              ],
                                            ),
                                            child: Column(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              spacing: 0,
                                              children: [
                                                Container(
                                                  width: double.infinity,
                                                  height: 72.54,
                                                  padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 16),
                                                  decoration: ShapeDecoration(
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(
                                                        width: 0.55,
                                                        color: const Color(0xFF222633),
                                                      ),
                                                    ),
                                                  ),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.start,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    spacing: 16,
                                                    children: [
                                                      Container(
                                                        width: 40,
                                                        height: 40,
                                                        decoration: ShapeDecoration(
                                                          color: const Color(0xFF222633),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(
                                                              width: 0.55,
                                                              color: const Color(0xFF2A2F3A),
                                                            ),
                                                            borderRadius: BorderRadius.circular(18372300),
                                                          ),
                                                        ),
                                                        child: Row(
                                                          mainAxisSize: MainAxisSize.min,
                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                          crossAxisAlignment: CrossAxisAlignment.center,
                                                          children: [
                                                            Text(
                                                              '🏠',
                                                              style: TextStyle(
                                                                color: const Color(0xFFEDEFF3),
                                                                fontSize: 16,
                                                                fontFamily: 'Inter',
                                                                fontWeight: FontWeight.w500,
                                                                height: 1.50,
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                      Expanded(
                                                        child: Container(
                                                          height: 37.59,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 0,
                                                                child: Container(
                                                                  width: 265.07,
                                                                  height: 19.59,
                                                                  clipBehavior: Clip.antiAlias,
                                                                  decoration: BoxDecoration(),
                                                                  child: Stack(
                                                                    children: [
                                                                      Positioned(
                                                                        left: 0,
                                                                        top: 0.10,
                                                                        child: Text(
                                                                          'Roommates',
                                                                          style: TextStyle(
                                                                            color: const Color(0xFFEDEFF3),
                                                                            fontSize: 14,
                                                                            fontFamily: 'Inter',
                                                                            fontWeight: FontWeight.w500,
                                                                            height: 1.40,
                                                                          ),
                                                                        ),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 20.23,
                                                                child: Text(
                                                                  '2 members',
                                                                  style: TextStyle(
                                                                    color: const Color(0xFF8E7CFF),
                                                                    fontSize: 12,
                                                                    fontFamily: 'Inter',
                                                                    fontWeight: FontWeight.w400,
                                                                    height: 1.50,
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Container(
                                                        width: 29.87,
                                                        height: 20.80,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: -0.45,
                                                              child: Text(
                                                                '\$67',
                                                                style: TextStyle(
                                                                  color: const Color(0xFF8E7CFF),
                                                                  fontSize: 16,
                                                                  fontFamily: 'Inter',
                                                                  fontWeight: FontWeight.w600,
                                                                  height: 1.30,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                                Container(
                                                  width: double.infinity,
                                                  height: 71.99,
                                                  padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 16),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.start,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    spacing: 16,
                                                    children: [
                                                      Container(
                                                        width: 40,
                                                        height: 40,
                                                        decoration: ShapeDecoration(
                                                          color: const Color(0xFF222633),
                                                          shape: RoundedRectangleBorder(
                                                            side: BorderSide(
                                                              width: 0.55,
                                                              color: const Color(0xFF2A2F3A),
                                                            ),
                                                            borderRadius: BorderRadius.circular(18372300),
                                                          ),
                                                        ),
                                                        child: Row(
                                                          mainAxisSize: MainAxisSize.min,
                                                          mainAxisAlignment: MainAxisAlignment.center,
                                                          crossAxisAlignment: CrossAxisAlignment.center,
                                                          children: [
                                                            Text(
                                                              '🏔️',
                                                              style: TextStyle(
                                                                color: const Color(0xFFEDEFF3),
                                                                fontSize: 16,
                                                                fontFamily: 'Inter',
                                                                fontWeight: FontWeight.w500,
                                                                height: 1.50,
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                      Expanded(
                                                        child: Container(
                                                          height: 37.59,
                                                          child: Column(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.start,
                                                            crossAxisAlignment: CrossAxisAlignment.start,
                                                            spacing: 0,
                                                            children: [
                                                              Container(
                                                                width: double.infinity,
                                                                height: 19.59,
                                                                clipBehavior: Clip.antiAlias,
                                                                decoration: BoxDecoration(),
                                                                child: Stack(
                                                                  children: [
                                                                    Positioned(
                                                                      left: 0,
                                                                      top: 0.10,
                                                                      child: Text(
                                                                        'Trip to Tahoe',
                                                                        style: TextStyle(
                                                                          color: const Color(0xFFEDEFF3),
                                                                          fontSize: 14,
                                                                          fontFamily: 'Inter',
                                                                          fontWeight: FontWeight.w500,
                                                                          height: 1.40,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ],
                                                                ),
                                                              ),
                                                              Container(
                                                                width: double.infinity,
                                                                height: 18,
                                                                child: Stack(
                                                                  children: [
                                                                    Positioned(
                                                                      left: 0,
                                                                      top: 0.64,
                                                                      child: Text(
                                                                        '3 members',
                                                                        style: TextStyle(
                                                                          color: const Color(0xFF8E7CFF),
                                                                          fontSize: 12,
                                                                          fontFamily: 'Inter',
                                                                          fontWeight: FontWeight.w400,
                                                                          height: 1.50,
                                                                        ),
                                                                      ),
                                                                    ),
                                                                  ],
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Container(
                                                        width: 36.77,
                                                        height: 20.80,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: -0.45,
                                                              child: Text(
                                                                '\$155',
                                                                style: TextStyle(
                                                                  color: const Color(0xFF8E7CFF),
                                                                  fontSize: 16,
                                                                  fontFamily: 'Inter',
                                                                  fontWeight: FontWeight.w600,
                                                                  height: 1.30,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: double.infinity,
                                      height: 101.59,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        spacing: 11.99,
                                        children: [
                                          Container(
                                            width: double.infinity,
                                            height: 16.50,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 4,
                                                  top: 0.64,
                                                  child: Text(
                                                    'SETTLED',
                                                    style: TextStyle(
                                                      color: const Color(0xFF9AA0A6),
                                                      fontSize: 11,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w500,
                                                      height: 1.50,
                                                      letterSpacing: 0.88,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Container(
                                            width: double.infinity,
                                            height: 73.09,
                                            padding: const EdgeInsets.all(0.55),
                                            clipBehavior: Clip.antiAlias,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1A1D24),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 0.55,
                                                  color: const Color(0xFF2A2F3A),
                                                ),
                                                borderRadius: BorderRadius.circular(18),
                                              ),
                                              shadows: [
                                                BoxShadow(
                                                  color: Color(0x66000000),
                                                  blurRadius: 32,
                                                  offset: Offset(0, 8),
                                                  spreadRadius: 0,
                                                )
                                              ],
                                            ),
                                            child: Column(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Container(
                                                  width: double.infinity,
                                                  height: 71.99,
                                                  padding: const EdgeInsets.symmetric(horizontal: 19.99, vertical: 16),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.start,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    spacing: 16,
                                                    children: [
                                                      Opacity(
                                                        opacity: 0.50,
                                                        child: Container(
                                                          width: 40,
                                                          height: 40,
                                                          decoration: ShapeDecoration(
                                                            color: const Color(0xFF222633),
                                                            shape: RoundedRectangleBorder(
                                                              side: BorderSide(
                                                                width: 0.55,
                                                                color: const Color(0xFF2A2F3A),
                                                              ),
                                                              borderRadius: BorderRadius.circular(18372300),
                                                            ),
                                                          ),
                                                          child: Row(
                                                            mainAxisSize: MainAxisSize.min,
                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                            crossAxisAlignment: CrossAxisAlignment.center,
                                                            children: [
                                                              Text(
                                                                '🍱',
                                                                style: TextStyle(
                                                                  color: const Color(0xFFEDEFF3),
                                                                  fontSize: 16,
                                                                  fontFamily: 'Inter',
                                                                  fontWeight: FontWeight.w500,
                                                                  height: 1.50,
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Expanded(
                                                        child: Container(
                                                          height: 37.59,
                                                          child: Stack(
                                                            children: [
                                                              Positioned(
                                                                left: 0,
                                                                top: 0,
                                                                child: Container(
                                                                  width: 282.61,
                                                                  height: 19.59,
                                                                  clipBehavior: Clip.antiAlias,
                                                                  decoration: BoxDecoration(),
                                                                  child: Stack(
                                                                    children: [
                                                                      Positioned(
                                                                        left: 0,
                                                                        top: 0.10,
                                                                        child: Text(
                                                                          'Office Lunch',
                                                                          style: TextStyle(
                                                                            color: const Color(0xFFEDEFF3),
                                                                            fontSize: 14,
                                                                            fontFamily: 'Inter',
                                                                            fontWeight: FontWeight.w500,
                                                                            height: 1.40,
                                                                          ),
                                                                        ),
                                                                      ),
                                                                    ],
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 0,
                                                                top: 20.23,
                                                                child: Text(
                                                                  'All settled up',
                                                                  style: TextStyle(
                                                                    color: const Color(0xFF9AA0A6),
                                                                    fontSize: 12,
                                                                    fontFamily: 'Inter',
                                                                    fontWeight: FontWeight.w400,
                                                                    height: 1.50,
                                                                  ),
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Container(
                                                        width: 12.33,
                                                        height: 20.99,
                                                        child: Stack(
                                                          children: [
                                                            Positioned(
                                                              left: 0,
                                                              top: -0.36,
                                                              child: Text(
                                                                '✓',
                                                                style: TextStyle(
                                                                  color: const Color(0xFF9AA0A6),
                                                                  fontSize: 14,
                                                                  fontFamily: 'Inter',
                                                                  fontWeight: FontWeight.w400,
                                                                  height: 1.50,
                                                                ),
                                                              ),
                                                            ),
                                                          ],
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: double.infinity,
                                      height: 62.78,
                                      decoration: ShapeDecoration(
                                        shape: RoundedRectangleBorder(
                                          side: BorderSide(
                                            width: 1.64,
                                            color: const Color(0xFF2A2F3A),
                                          ),
                                          borderRadius: BorderRadius.circular(18),
                                        ),
                                      ),
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 150.13,
                                            top: 23.39,
                                            child: Container(
                                              width: 16,
                                              height: 16,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: BoxDecoration(),
                                              child: Stack(),
                                            ),
                                          ),
                                          Positioned(
                                            left: 174.13,
                                            top: 22.28,
                                            child: Text(
                                              'Create Group',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: const Color(0xFF9AA0A6),
                                                fontSize: 13,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w600,
                                                height: 1.50,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 19.99,
                              top: 156.06,
                              child: Container(
                                width: 408.01,
                                height: 46.08,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 408.01,
                                        height: 46.08,
                                        padding: const EdgeInsets.only(
                                          top: 12,
                                          left: 44,
                                          right: 16,
                                          bottom: 12,
                                        ),
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF1A1D24),
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(
                                              width: 0.55,
                                              color: const Color(0xFF2A2F3A),
                                            ),
                                            borderRadius: BorderRadius.circular(14),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          children: [
                                            Text(
                                              'Search groups...',
                                              style: TextStyle(
                                                color: const Color(0xFF5A5F6A),
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 16,
                                      top: 15.04,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: BoxDecoration(),
                                        child: Stack(),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 780.39,
                child: Container(
                  width: 492.78,
                  height: 71.03,
                  padding: const EdgeInsets.only(top: 0.55, left: 22.39, right: 22.40),
                  decoration: ShapeDecoration(
                    color: const Color(0xF21A1D24),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.55,
                        color: const Color(0xFF2A2F3A),
                      ),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 70.49,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 21.51,
                              top: 8,
                              child: Container(
                                width: 68.23,
                                height: 54.49,
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 4,
                                  children: [
                                    Container(
                                      width: 22,
                                      height: 22,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Container(
                                            width: double.infinity,
                                            height: 22,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 28.24,
                                      height: 12.50,
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            'Home',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF9AA0A6),
                                              fontSize: 10,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.25,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 132.76,
                              top: 8,
                              child: Container(
                                width: 72.82,
                                height: 54.49,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 24.31,
                                      top: 4.90,
                                      child: Container(
                                        width: 24.20,
                                        height: 24.20,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              width: double.infinity,
                                              height: 24.20,
                                              clipBehavior: Clip.antiAlias,
                                              decoration: BoxDecoration(),
                                              child: Stack(),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 19.09,
                                      top: 33.94,
                                      child: Container(
                                        width: 34.65,
                                        height: 12.60,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0.09,
                                              top: -0.24,
                                              child: Text(
                                                'People',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: const Color(0xFF4F6EF7),
                                                  fontSize: 10.50,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.25,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 34.41,
                                      top: -2,
                                      child: Container(
                                        width: 4,
                                        height: 4,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF4F6EF7),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(18372300),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 248.60,
                              top: 8,
                              child: Container(
                                width: 64.01,
                                height: 54.49,
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 4,
                                  children: [
                                    Container(
                                      width: 22,
                                      height: 22,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Container(
                                            width: double.infinity,
                                            height: 22,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 24.02,
                                      height: 12.50,
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            'Scan',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF9AA0A6),
                                              fontSize: 10,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.25,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 355.63,
                              top: 8,
                              child: Container(
                                width: 70.85,
                                height: 54.49,
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 4,
                                  children: [
                                    Container(
                                      width: 22,
                                      height: 22,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Container(
                                            width: double.infinity,
                                            height: 22,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 30.87,
                                      height: 12.50,
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            'Profile',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFF9AA0A6),
                                              fontSize: 10,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.25,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}